### ISSUE TITLE
randint attribute not found in dumpy Generator.

### ISSUE THREAD

**Issue by raymondchua** [qlan3/gym-games#4]
```
self.opt_a = self.rng.randint(low=0, high=self.action_space.n, size=self.horizon)
self.opt_b = self.rng.randint(low=0, high=self.action_space.n, size=self.horizon)

```
[These two lines of code](https://github.com/qlan3/gym-games/blob/c272eedcd5bd23a3b6382632d80da09b3344a3a1/gym_exploration/envs/diabolical_comb_lock.py#L102) throw an error: `AttributeError: 'numpy.random._generator.Generator' object has no attribute 'randint'  `

It seems that it could be fix by replacing with `randint` with `integers`. 

I am using numpy version 1.24.1.

**Comment by qlan3** [comment]
I just checked my numpy version which is 1.22.3. Can you try this version to see if it works for you?
Maybe I should also add a requirement file...
