### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement ple==0.0.1

### ISSUE THREAD

**Issue by Yang1231** [qlan3/gym-games#5]
How can I deal with this problem? I have already installed all requirements except gym_game. It is an error happed :ERROR: Could not find a version that satisfies the requirement ple==0.0.1 (from gym-games) (from versions: none)
ERROR: No matching distribution found for ple==0.0.1 .
I cant find the ple package. Please help.

**Comment by qlan3** [comment]
Did you try `pip install git+https://github.com/ntasfi/PyGame-Learning-Environment.git`?

**Comment by Yang1231** [comment]
> Did you try `pip install git+https://github.com/ntasfi/PyGame-Learning-Environment.git`?

Yes, I have tried it. I follow the gym_game step. Stopped at ple.

**Comment by Yang1231** [comment]
Is it related to the version of python? I'm using 3.10.

**Comment by qlan3** [comment]
It could be. I remembered that Python 3.7 or 3.8 works. You could give it a try.

**Comment by Yang1231** [comment]
Should I have to install brew install sdl sdl_ttf sdl_image sdl_mixer portmidi
pip install pygame==1.9.6？

**Comment by qlan3** [comment]
I'm not sure. The best way to find out is to try it. You may also refer to this page for more info: https://www.pygame.org/wiki/GettingStarted#Pygame%20Installation
